[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
matching_engine = "3MSz7Kkyf6yXC1puWY8gofiPqCHPqYYMdMeZd3KYDi3y"

[programs.devnet]
matching_engine = "3MSz7Kkyf6yXC1puWY8gofiPqCHPqYYMdMeZd3KYDi3y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts --ignore tests/helpers/**/*.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/arnabnandi/matching_engine/artifacts/arcium_program_0.3.0.so"
