[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
matching_engine = "AEzijpcr55b6xPtNHXqN57B8BoXbAeHjsLNKo6g4pYPh"

[programs.devnet]
matching_engine = "AEzijpcr55b6xPtNHXqN57B8BoXbAeHjsLNKo6g4pYPh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts --ignore tests/helpers/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/arnabnandi/matching_engine/artifacts/arcium_program_0.3.0.so"
